import type { Metadata } from "next";
import { Sora, Open_Sans } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${openSans.variable} flex min-h-screen w-full flex-col antialiased`}
      >
        <Navbar />
        <main className="mx-auto max-w-screen-lg w-full px-2 lg:px-0 py-8">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
