on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build 

    - name: Lint
      run: npm run lint
